### ISSUE TITLE
J2C Sync

### ISSUE THREAD

**Issue by xiruzhu** [anrl/JAM#12]
On my ubuntu machine, I keep getting Unhandled rejection No devices connected. 
Will attempt to fix it.

**Comment by anrl** [comment]
This is normal if you try to run sync with no devices connected. This could also happen if you set the timeout too high (I mean heartbeat value) and try to run the J2C sync. There won't be any devices registered and you will get the exception thrown.

**Comment by xiruzhu** [comment]
Ok it works, even with 3 programs where everyone will get the message so it's like a real chat program.But there seems to be a bug where the message gets displayed 3 times for everyone. Are you making the system send the function three times?I'll try to fix that.Xiru Zhu 

    On Saturday, June 11, 2016 4:23 PM, anrl <notifications@github.com> wrote:
 

 This is normal if you try to run sync with no devices connected. This could also happen if you set the timeout too high (I mean heartbeat value) and try to run the J2C sync. There won't be any devices registered and you will get the exception thrown.—
