### ISSUE TITLE
Maybe can't put capital letter in variable id in C

### ISSUE THREAD

**Issue by Wenger** [anrl/JAM#16]

**Comment by xiruzhu** [comment]
I bricked it

**Comment by anrl** [comment]
What does this mean.. I don't mean the brick part. 
So no capitals in ID? Is this a restriction of the grammar?

**Comment by Wenger** [comment]
I was a bit to eager to open an issue. The bug wasn't what I thought it was, and is working correctly according to design.

**Comment by anrl** [comment]
Thanks for spamming the issue system!
